Repository weaverse-techtide/weaverse-backend, pull requests merged in 2024-10, with the labels that each got.

#132 fix: settings 파일 수정
  weaverse/settings.py
Labels: bug

#135 134 인증 테스트 오류settings 파일 수정
  jwtauth/test/test_authentication.py
  weaverse/settings.py
Labels: bug

#138 refactor: accounts/views.py 수정 - 토큰 임포트 삭제
  accounts/views.py
Labels: enhancement

#159 Yujeong/accounts 테스트 에러 및 이미지 필드 추가
  accounts/serializers.py
Labels: enhancement

#165 Yujeong/accounts 앱의 관리자 페이지 에러(FieldError) 해결
  accounts/admin.py
  accounts/test/test_accounts_admin.py
Labels: bug

#178 Yujeong/materials 앱
  materials/migrations/0008_alter_image_options_alter_video_options_and_more.py
  materials/models.py
  materials/serializers.py
  materials/urls.py
  materials/views.py
Labels: enhancement

#180 Nathan/social login3
  README.md
  jwtauth/views.py
  weaverse/settings.py
Labels: documentation
